### ISSUE TITLE
Default name

### ISSUE THREAD

**Issue by lmarburger** [paulhammond/slackcat#3]
Is there a reason the default name isn't blank? I tend to give integrations a default name in the hook itself. I'm sure there's reason to use the user@system. Personally, I haven't had a need for it.

P.S. Awesome idea!

**Comment by paulhammond** [comment]
The user@system default is intended to provide some kind of attribution when using slackcat in an adhoc way.

But you're right that for many uses you might want to use the pattern of setting a default name in the hook, so 0b27c09a0564ecef8db2f8b182be30fe242becda adds the ability to set a default username in the config file. This default can be blank which will cause the default hook username to be used.

I think this gives you what you want! If not please reopen...
